'use strict';
// Copies the xterm.js UMD builds out of node_modules into public/vendor/ so
// the renderer stays a plain-script-tag page with no bundler. The @xterm
// packages are devDependencies: they never run in Node, they are only the
// source of these static files. vendor-check.js (in npm test) fails when the
// copies drift from the installed versions, so upgrades are deliberate.

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const destDir = path.join(root, 'public', 'vendor', 'xterm');

// [package, file inside package, destination name]
const FILES = [
    ['@xterm/xterm', 'lib/xterm.js', 'xterm.js'],
    ['@xterm/xterm', 'css/xterm.css', 'xterm.css'],
    ['@xterm/addon-clipboard', 'lib/addon-clipboard.js', 'addon-clipboard.js'],
    ['@xterm/addon-fit', 'lib/addon-fit.js', 'addon-fit.js'],
    ['@xterm/addon-search', 'lib/addon-search.js', 'addon-search.js'],
    ['@xterm/addon-serialize', 'lib/addon-serialize.js', 'addon-serialize.js'],
    ['@xterm/addon-webgl', 'lib/addon-webgl.js', 'addon-webgl.js'],
];

fs.mkdirSync(destDir, { recursive: true });

const manifest = [];
for (const [pkg, rel, dest] of FILES) {
    const src = path.join(root, 'node_modules', pkg, rel);
    fs.copyFileSync(src, path.join(destDir, dest));
    const version = JSON.parse(fs.readFileSync(
        path.join(root, 'node_modules', pkg, 'package.json'), 'utf8')).version;
    manifest.push({ pkg, version, file: dest });
    console.log(`vendored ${dest} from ${pkg}@${version}`);
}

// Machine-readable so vendor-check.js can verify; the .md rendering is for
// humans browsing the repo.
const byPkg = new Map(manifest.map((m) => [m.pkg, m.version]));
const lines = ['# Vendored files', '',
    'Generated by tools/vendor-sync.js - do not edit by hand.', ''];
for (const [pkg, version] of byPkg) lines.push(`- ${pkg}@${version}`);
lines.push('');
fs.writeFileSync(path.join(destDir, 'VENDORED.md'), lines.join('\n'));
fs.writeFileSync(path.join(destDir, 'vendored.json'),
    JSON.stringify(manifest, null, 2) + '\n');
